### PR TITLE
Add Nicholas Henry to Alumni

### PR DESCRIPTION
**Pull request by nicholasjhenry**
Since I've taught at the last three I thought it would OK to add myself to the Alumni ;-) Cheers!

### CODE REVIEW

**Comment by benichu** [comment]
You were forgotten because of elixir!

**Comment by sophiedeziel** [comment]
I think I accidentally removed you! I'm sorry!

**Comment by bluciam** [comment]
Would it be better to have links to each of the editions? Organizing team for XXXX, where XXXX is the year with a link a nice looking page, resembling what the current looks like? That would be easier to maintain in the future.
Besides, alumni is for people who took the workshop. No?

**Comment by sophiedeziel** [comment]
If we can find complete information, yes it would be better to tell who participated when. I don't think it has to be separate pages, but I like the idea in general

**Comment by bluciam** [comment]
Ok, I could set out the layout. How many Rails bridge have been there in Montreal?
The idea of a separate pages is that the cutting and pasting for the future I think will be easier.

**Comment by sophiedeziel** [comment]
Let's create an issue to have that conversation. A closed pull-request is not the most convenient place to discuss about a new feature ;)

**Pull request merged**
